development:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

test: &TEST
  adapter: postgresql
  host: localhost
  username: postgres
  password:
  database: crewmate

production:
  adapter: postgresql
  host: localhost
  username: postgres
  password:
  database: crewmate

cucumber:
  <<: *TEST
